apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8s-lib-ci-rbac
  annotations:
    github.com/project-slug: mattjmorrison-homelab/k8s-lib-ci-rbac
spec:
  type: deployment-config
  owner: mattjmorrison-homelab
  lifecycle: experimental
  system: rbac
